version: '3'
services:
  postgres:
    env_file: ./.env
    image: arielafonso/postgres:1.0
    restart: always
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    networks:
      - app-net
  
  python:
    build:
      context: .
    depends_on:
      - postgres
    volumes:
      - ./:/app
    networks:
      - app-net

networks:
  app-net:
