version: "3"
services:
  postgres:
    env_file: ./.env
    image: arielafonso/postgres:1.0
    restart: always
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    networks:
      - app-net
    container_name: "postgres"

  python:
    build:
      context: .
    depends_on:
      - postgres
    volumes:
      - ./:/app
    networks:
      - app-net
    stdin_open: true
    tty: true
    container_name: "python"

volumes:
  postgres:

networks:
  app-net:
